# this Dockerfile is setup specifically to work with opeNode's Dockerfile restrictions
FROM google/dart
# debian-based image

ENV PORT=80
ENV INSTANCES=1

WORKDIR /opt/app

RUN echo 'set -e' > /usr/bin/start.sh # this is the script which will run on start

RUN echo 'pub get' >> /usr/bin/start.sh
RUN echo 'pub get --offline' >> /usr/bin/start.sh

# build snapshot (reduces memory footprint ~2.5x), run server
RUN echo 'dart --snapshot=server.dart.snapshot bin/server.dart' >> /usr/bin/start.sh
RUN echo 'dart server.dart.snapshot' >> /usr/bin/start.sh